name: Create Release

on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: patch | minor | major
        required: true
        default: patch
        type: choice
        options: [patch, minor, major]

jobs:
  create:
    uses: michael-lim-watcha/watcha-actions-platform/.github/workflows/reusable-create-release.yml@main
    with:
      version_bump: ${{ inputs.version_bump }}
    secrets: inherit
